// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYdP5cEf4jompdtsJDRAZAwCVZ6kEJPk',
    appId: '1:183479258366:web:6f56536b4e7ea164fa29af',
    messagingSenderId: '183479258366',
    projectId: 'flixid-course-d6798',
    authDomain: 'flixid-course-d6798.firebaseapp.com',
    storageBucket: 'flixid-course-d6798.appspot.com',
    measurementId: 'G-VCEPWPT59X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8XzeodBuhVozZ0rB_3X-1ipx1ORXqwmg',
    appId: '1:183479258366:android:3344f5c1f0e96402fa29af',
    messagingSenderId: '183479258366',
    projectId: 'flixid-course-d6798',
    storageBucket: 'flixid-course-d6798.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXYdP5cEf4jompdtsJDRAZAwCVZ6kEJPk',
    appId: '1:183479258366:web:f4adbd766576634dfa29af',
    messagingSenderId: '183479258366',
    projectId: 'flixid-course-d6798',
    authDomain: 'flixid-course-d6798.firebaseapp.com',
    storageBucket: 'flixid-course-d6798.appspot.com',
    measurementId: 'G-PT2MHKN2JK',
  );
}
